### ISSUE TITLE
Add comparison with Phoenix to README

### ISSUE THREAD

**Issue by funny-falcon** [waterguo/antsdb#1]
Apache Phoenix also provides SQL layer on top of HBase and oriented towards OLTP.
How AntsDB compares to Phoenix?

**Comment by funny-falcon** [comment]
Phoenix also has real transactions.

Any way, this comparison should be in README or Wiki.

**Comment by waterguo** [comment]
True. I will mask it.

**Comment by waterguo** [comment]
all done. thanks for you suggestion.
