### ISSUE TITLE
怎么安装使用antsdb

### ISSUE THREAD

**Issue by SKY-Hao** [waterguo/antsdb#11]
您好，怎么安装使用antsdb有详细文档吗

**Comment by waterguo** [comment]
首先下载最新版本  https://antsdb.com/downloads/antsdb-latest.tar.gz

关于安装， 参见下面 2 个页面
https://github.com/waterguo/antsdb/wiki/Installation
https://github.com/waterguo/antsdb/wiki/Configuration

**Comment by SKY-Hao** [comment]
我如何使用呢？方便告诉下吗


| |
黄
|
|
hth_swp@163.com
|
签名由网易邮箱大师定制
在2019年1月3日 11:12，Water Guo<notifications@github.com> 写道：

首先下载最新版本 https://antsdb.com/downloads/antsdb-latest.tar.gz

关于安装， 参见下面 2 个页面
https://github.com/waterguo/antsdb/wiki/Installation
https://github.com/waterguo/antsdb/wiki/Configuration

**Comment by waterguo** [comment]
简化一下有下面几个步骤
1. 找一台 linux 服务器 tar xzvf <下载的tar.gz文件>
2.  cp antsdb/conf/conf.properties.template antsdb/conf/conf.properties
3. 打开 antsdb/conf/conf.properties, 找到 humpback.hbase-conf=, 填上你 hbase-site.xml 文件的位置， 使用绝对路径
4. antsdb/bin/antsdb start 启动
5.a 如果你用 mysql 命令行， mysql -h <antsdb 的 IP 地址>
5.b 如果你用 navicat, 直接使用 antsdb 机器的 IP 地址

你可是使用 mysql 的驱动程序， 界面， 命令行连接 antsdb,

**Comment by SKY-Hao** [comment]
我是不是还得需要安装mysql驱动？
方便加个微信吗？
我的微信：h787501374


| |
黄
|
|
hth_swp@163.com
|
签名由网易邮箱大师定制
在2019年1月3日 11:51，Water Guo<notifications@github.com> 写道：

简化一下有下面几个步骤

找一台 linux 服务器 tar xzvf <下载的tar.gz文件>
cp antsdb/conf/conf.properties.template antsdb/conf/conf.properties
打开 antsdb/conf/conf.properties, 找到 humpback.hbase-conf=, 填上你 hbase-site.xml 文件的位置， 使用绝对路径
antsdb/bin/antsdb start 启动
5.a 如果你用 mysql 命令行， mysql -h <antsdb 的 IP 地址>
5.b 如果你用 navicat, 直接使用 antsdb 机器的 IP 地址

你可是使用 mysql 的驱动程序， 界面， 命令行连接 antsdb,
